theme: jekyll-theme-cayman
locale: ja-JP
title: MYukkuriVoice
show_downloads: true
help_url: https://taku-o.github.io/myukkurivoice/help
latest_release_url: https://github.com/taku-o/myukkurivoice/releases/latest
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
