# require NPM_AUTH_TOKEN
#   add GitHub npm token to Projects Secrets
# require SLACK_WEBHOOK
#   add Slack incoming-webhooks URL to Projects Secrets
#   https://slack.com/apps/A0F7XDUAZ-incoming-webhooks

name: lint

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-10.14
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [12.4.0]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: cache node environment bk1
        id: cache-node-bk1
        uses: actions/cache@v1
        with:
          path: ~/.npm_bk1
          key: ${{ runner.os }}-node-bk1-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-bk1
      - name: cache node environment bk2
        id: cache-node-bk2
        uses: actions/cache@v1
        with:
          path: ~/.npm_bk2
          key: ${{ runner.os }}-node-bk2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-bk2
      - name: restore cache node environment bk1, bk2
        if: steps.cache-node-bk1.outputs.cache-hit == 'true'
        run: |
          mkdir ~/.npm
          mv ~/.npm_bk1/* ~/.npm
          mv ~/.npm_bk2/* ~/.npm

      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
      - name: npm install
        if: steps.cache-node-bk1.outputs.cache-hit != 'true'
        run: |
          npm install
      - name: npm not install
        if: steps.cache-node-bk1.outputs.cache-hit == 'true'
        run: |
          echo "cache hit"

      - name: gulp lint
        run: |
          npx gulp lint

      - name: gulp tsc
        run: |
          npx gulp tsc

      - name: gulp format
        run: |
          npx gulp format

      - name: gulp about
        run: |
          npx gulp about

      - name: git status -s wc
        run: |
          test 0 -ge `git status -s | wc -l`

      - name: backup cache node environment bk1, bk2
        if: steps.cache-node-bk1.outputs.cache-hit != 'true'
        run: |
          mkdir ~/.npm_bk1
          mkdir ~/.npm_bk2
          mv ~/.npm/[@A-Z_][a-l]* ~/.npm_bk1
          mv ~/.npm/[m]* ~/.npm_bk2

